version: 0.2

env:
  variables:
    REPOSITORY_URI: 927450005871.dkr.ecr.us-east-1.amazonaws.com/winde-registry
    AWS_REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo "Verifying ECR repository exists..."
      - aws ecr describe-repositories --repository-names winde-registry --region $AWS_REGION || aws ecr create-repository --repository-name winde-registry --region $AWS_REGION
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo $IMAGE_TAG > image_tag.txt

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$(cat image_tag.txt)

  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$(cat image_tag.txt)
      - printf '[{"name":"winde-registry","imageUri":"%s"}]' $REPOSITORY_URI:$(cat image_tag.txt) > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/aws.jar